#!/bin/bash
#NOTE: DO NOT EDIT THIS FILE-- MAY RESULT IN INCOMPLETE SUBMISSIONS

NOTEBOOKS="RNN_Captioning.ipynb
    LSTM_Captioning.ipynb
    NetworkVisualization-TensorFlow.ipynb
    StyleTransfer-TensorFlow.ipynb
    Generative_Adversarial_Networks_TF.ipynb"

CODE=cs231n/"classifiers/rnn.py
    cs231n/rnn_layers.py"

REMOTE_DIR="cs231n-2019-assignment3"
ZIP_FILENAME="a3.zip"

FILES="${NOTEBOOKS} ${CODE}"
for FILE in ${FILES}
do
	if [ ! -f ${FILE} ]; then
		echo "Required file ${FILE} not found, Exiting."
		exit 0
	fi
done
if [ -d ${REMOTE_DIR} ]; then
	rm -r ${REMOTE_DIR}
fi

echo "### Zipping file ###"
zip -r ${ZIP_FILENAME} . -x '*.ipynb_checkpoints*' -i '*.ipynb' '*.py' > assignment_zip.log
echo ""

echo "Please rename ${ZIP_FILENAME} into a3_<AU-username>_<first-name>_<last-name>.zip and upload to Canvas."
